#!/bin/bash
#
# Tempo Worklogs Upload Script
# 
# This script uploads time entries to Tempo via the REST API.
# Generated by convert_to_tempo.py
#
# Prerequisites:
# - Tempo API token (set in this script or via TEMPO_API_TOKEN env var)
# - jq (for JSON processing): sudo apt-get install jq
# - curl (usually pre-installed)
#
# Usage:
#   chmod +x Ruben van der Linde_overtime_tempo_upload.sh
#   ./Ruben van der Linde_overtime_tempo_upload.sh
#

set -e  # Exit on error

# Configuration
TEMPO_API_TOKEN="$YOUR_TEMPO_API_TOKEN"
JIRA_BASE_URL="https://your-domain.atlassian.net"
JSON_FILE="/home/rubenlinde/nextcloud-docker-dev/workspace/server/apps-extra/timetracking/Ruben_van_der_Linde/Ruben van der Linde_overtime_tempo_api.json"
TEMPO_API_URL="$JIRA_BASE_URL/rest/tempo-timesheets/4/worklogs"

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "Error: jq is not installed. Install it with: sudo apt-get install jq"
    exit 1
fi

# Check if JSON file exists
if [ ! -f "$JSON_FILE" ]; then
    echo "Error: JSON file not found: $JSON_FILE"
    exit 1
fi

# Check if API token is set
if [ -z "$TEMPO_API_TOKEN" ]; then
    echo "Error: TEMPO_API_TOKEN not set"
    echo "Set it in this script or export it: export TEMPO_API_TOKEN='your-token'"
    exit 1
fi

echo "=========================================="
echo "Tempo Worklogs Upload"
echo "=========================================="
echo ""
echo "JSON file: $JSON_FILE"
echo "Tempo API URL: $TEMPO_API_URL"
echo ""

# Count total worklogs
TOTAL=$(jq length "$JSON_FILE")
echo "Total worklogs to upload: $TOTAL"
echo ""

# Confirmation
read -p "Do you want to proceed with upload? (yes/no): " CONFIRM
if [ "$CONFIRM" != "yes" ]; then
    echo "Upload cancelled."
    exit 0
fi

# Upload each worklog
SUCCESS=0
FAILED=0
COUNTER=1

while IFS= read -r worklog; do
    echo "[$COUNTER/$TOTAL] Uploading worklog..."
    
    # Extract date for logging
    DATE=$(echo "$worklog" | jq -r '.startDate')
    HOURS=$(echo "$worklog" | jq -r '.timeSpentSeconds / 3600')
    
    # Upload via API
    RESPONSE=$(curl -s -w "\n%{http_code}" \
        -X POST "$TEMPO_API_URL" \
        -H "Authorization: Bearer $TEMPO_API_TOKEN" \
        -H "Content-Type: application/json" \
        -d "$worklog")
    
    # Parse response
    HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
    BODY=$(echo "$RESPONSE" | sed '$d')
    
    if [ "$HTTP_CODE" -eq 200 ] || [ "$HTTP_CODE" -eq 201 ]; then
        echo "  ✓ Success: $DATE - ${HOURS}h"
        ((SUCCESS++))
    else
        echo "  ✗ Failed: $DATE - ${HOURS}h (HTTP $HTTP_CODE)"
        echo "    Response: $BODY"
        ((FAILED++))
    fi
    
    ((COUNTER++))
    
    # Rate limiting: small delay between requests
    sleep 0.5
done < <(jq -c '.[]' "$JSON_FILE")

echo ""
echo "=========================================="
echo "Upload Complete"
echo "=========================================="
echo "Success: $SUCCESS"
echo "Failed: $FAILED"
echo "Total: $TOTAL"
echo ""

if [ $FAILED -gt 0 ]; then
    echo "Some uploads failed. Check error messages above."
    exit 1
fi

echo "All worklogs uploaded successfully!"
