#!/usr/bin/env python3
"""
Update Jira issues with WBSO field values and commit comments.
Reads from jira-update-plan.json, sets customfield_10038 and adds comments.
Saves progress so it can be resumed if interrupted.
"""

import json
import time
import sys
import os
from datetime import datetime
from base64 import b64encode

try:
    import requests
except ImportError:
    print("Installing requests...")
    os.system("pip3 install requests --quiet")
    import requests

# Config
JIRA_URL = "https://conduction.atlassian.net"
JIRA_EMAIL = "ruben@conduction.nl"
JIRA_TOKEN = "REDACTED_JIRA_TOKEN_ROTATED_2026-05-28"

# Auth header
auth_str = b64encode(f"{JIRA_EMAIL}:{JIRA_TOKEN}".encode()).decode()
HEADERS = {
    "Authorization": f"Basic {auth_str}",
    "Content-Type": "application/json",
    "Accept": "application/json"
}

# DOCD issues can't have custom fields set (team-managed project)
SKIP_FIELD_PROJECTS = {"DOCD"}

PLAN_FILE = "wbso/raw/jira-update-plan.json"
PROGRESS_FILE = "wbso/raw/jira-update-progress.json"
RESULTS_FILE = "wbso/raw/jira-update-results.json"


def load_progress():
    """Load previously completed issues to enable resume."""
    if os.path.exists(PROGRESS_FILE):
        with open(PROGRESS_FILE) as f:
            return json.load(f)
    return {"completed": {}, "errors": {}}


def save_progress(progress):
    """Save progress after each issue."""
    with open(PROGRESS_FILE, "w") as f:
        json.dump(progress, f, indent=2)


def update_wbso_field(issue_key, options):
    """Set the WBSO/MIT checkbox field on a Jira issue."""
    url = f"{JIRA_URL}/rest/api/3/issue/{issue_key}"
    payload = {
        "fields": {
            "customfield_10038": [{"id": opt["id"]} for opt in options]
        }
    }
    resp = requests.put(url, headers=HEADERS, json=payload, timeout=30)
    return resp.status_code, resp.text


WBSO_NAMES = {
    "14283/119/01": "Codestack Merging 2025",
    "14283/119/02": "Isolated Search Engine 2025",
    "14283/120/01": "Gedistribueerde Rechtenengine 2025",
    "14283/120/02": "Fault Tolerant Task Orchestrator 2025",
}


def add_commit_comment(issue_key, data):
    """Add a formatted comment with commit details to a Jira issue."""
    commit_count = data["commit_count"]
    commits = data["commit_lines"]
    wbso_summary = data.get("wbso_summary", "")

    # Convert wbso_summary dict to readable string
    if isinstance(wbso_summary, dict):
        parts = []
        for code, count in sorted(wbso_summary.items(), key=lambda x: -x[1]):
            name = WBSO_NAMES.get(code, code)
            parts.append(f"{name}: {count} commits")
        wbso_summary = " | ".join(parts)

    # Build commit list (cap at 50)
    if len(commits) > 50:
        commit_text = "\n".join(commits[:50]) + f"\n\n... and {len(commits) - 50} more commits"
    else:
        commit_text = "\n".join(commits)

    # Build ADF comment
    content_blocks = [
        {
            "type": "heading",
            "attrs": {"level": 3},
            "content": [{"type": "text", "text": f"WBSO 2025 — {commit_count} commits"}]
        }
    ]

    if wbso_summary:
        content_blocks.append({
            "type": "paragraph",
            "content": [{"type": "text", "text": str(wbso_summary)}]
        })

    content_blocks.append({
        "type": "codeBlock",
        "attrs": {"language": "text"},
        "content": [{"type": "text", "text": commit_text}]
    })

    content_blocks.append({
        "type": "paragraph",
        "content": [
            {"type": "text", "text": "Auto-generated by WBSO 2025 commit analysis", "marks": [{"type": "em"}]}
        ]
    })

    url = f"{JIRA_URL}/rest/api/3/issue/{issue_key}/comment"
    payload = {
        "body": {
            "version": 1,
            "type": "doc",
            "content": content_blocks
        }
    }
    resp = requests.post(url, headers=HEADERS, json=payload, timeout=30)
    return resp.status_code, resp.text


def main():
    with open(PLAN_FILE) as f:
        plan = json.load(f)

    progress = load_progress()
    total = len(plan)
    already_done = len(progress["completed"])

    if already_done > 0:
        print(f"Resuming: {already_done}/{total} already completed, {len(progress['errors'])} previous errors")

    field_ok = 0
    field_skip = 0
    field_fail = 0
    comment_ok = 0
    comment_fail = 0
    start_time = time.time()

    for i, (issue_key, data) in enumerate(plan.items()):
        # Skip already completed
        if issue_key in progress["completed"]:
            continue

        project = issue_key.split("-")[0]
        result = {"field": None, "comment": None}

        # Step 1: Set WBSO field (skip DOCD)
        if project in SKIP_FIELD_PROJECTS:
            result["field"] = "skipped_team_managed"
            field_skip += 1
        else:
            for attempt in range(3):
                try:
                    status, body = update_wbso_field(issue_key, data["wbso_options"])
                    if status == 204:
                        result["field"] = "ok"
                        field_ok += 1
                        break
                    elif status == 429:
                        print(f"  Rate limited on field update for {issue_key}, waiting 10s...")
                        time.sleep(10)
                        continue
                    else:
                        result["field"] = f"error_{status}"
                        if attempt == 2:
                            field_fail += 1
                            error_detail = body[:200] if body else "no body"
                            progress["errors"][issue_key] = {"step": "field", "status": status, "detail": error_detail}
                        else:
                            time.sleep(2)
                except Exception as e:
                    result["field"] = f"exception: {str(e)[:100]}"
                    if attempt == 2:
                        field_fail += 1
                        progress["errors"][issue_key] = {"step": "field", "error": str(e)[:200]}
                    else:
                        time.sleep(2)

        time.sleep(0.3)

        # Step 2: Add commit comment
        for attempt in range(3):
            try:
                status, body = add_commit_comment(issue_key, data)
                if status in (200, 201):
                    result["comment"] = "ok"
                    comment_ok += 1
                    break
                elif status == 429:
                    print(f"  Rate limited on comment for {issue_key}, waiting 10s...")
                    time.sleep(10)
                    continue
                else:
                    result["comment"] = f"error_{status}"
                    if attempt == 2:
                        comment_fail += 1
                        error_detail = body[:200] if body else "no body"
                        progress["errors"][f"{issue_key}_comment"] = {"step": "comment", "status": status, "detail": error_detail}
                    else:
                        time.sleep(2)
            except Exception as e:
                result["comment"] = f"exception: {str(e)[:100]}"
                if attempt == 2:
                    comment_fail += 1
                    progress["errors"][f"{issue_key}_comment"] = {"step": "comment", "error": str(e)[:200]}
                else:
                    time.sleep(2)

        time.sleep(0.3)

        # Mark completed
        progress["completed"][issue_key] = result
        current = len(progress["completed"])

        # Progress update every 25 issues
        if current % 25 == 0 or current == total:
            elapsed = time.time() - start_time
            rate = (current - already_done) / elapsed if elapsed > 0 else 0
            remaining = (total - current) / rate if rate > 0 else 0
            print(f"[{current}/{total}] field: {field_ok} ok, {field_skip} skipped, {field_fail} failed | "
                  f"comments: {comment_ok} ok, {comment_fail} failed | "
                  f"~{remaining/60:.0f}min remaining")
            sys.stdout.flush()

        # Save progress every 10 issues
        if current % 10 == 0:
            save_progress(progress)

    # Final save
    save_progress(progress)

    # Summary
    elapsed = time.time() - start_time
    print(f"\n{'='*60}")
    print(f"WBSO Jira Update Complete")
    print(f"{'='*60}")
    print(f"Total issues processed: {len(progress['completed'])}")
    print(f"Field updates: {field_ok} ok, {field_skip} skipped (DOCD), {field_fail} failed")
    print(f"Comments added: {comment_ok} ok, {comment_fail} failed")
    print(f"Total errors: {len(progress['errors'])}")
    print(f"Time: {elapsed/60:.1f} minutes")
    print(f"{'='*60}")

    # Save final results
    with open(RESULTS_FILE, "w") as f:
        json.dump({
            "completed": len(progress["completed"]),
            "field_ok": field_ok,
            "field_skip": field_skip,
            "field_fail": field_fail,
            "comment_ok": comment_ok,
            "comment_fail": comment_fail,
            "errors": progress["errors"],
            "elapsed_minutes": round(elapsed / 60, 1),
            "timestamp": datetime.now().isoformat()
        }, f, indent=2)

    print(f"\nResults saved to {RESULTS_FILE}")
    if progress["errors"]:
        print(f"Errors saved to {PROGRESS_FILE}")
        print("\nFirst 5 errors:")
        for k, v in list(progress["errors"].items())[:5]:
            print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
